Use preload instead of includes
When `includes` is used, these `@works` return different queries (`left outer join` or `select in`).
https://github.com/annict/annict/blob/14e42a8463d7642bf5c3c9ac6c2cf1fd5502dbd2/app/controllers/works_controller.rb#L144-L146

And the following error has occurred.
```
NoMethodError: undefined method `[]' for nil:NilClass
  from app/views/works/display_options/_list_detailed.html.slim:37:in `block (4 levels) in _app_views_works_display_options__list_detailed_html_slim__1267502047880366728_70177150759060'
  from action_view/helpers/cache_helper.rb:253:in `write_fragment_for'
  from action_view/helpers/cache_helper.rb:243:in `fragment_for'
  from action_view/helpers/cache_helper.rb:169:in `cache'
  from app/views/works/display_options/_list_detailed.html.slim:36:in `block (3 levels) in _app_views_works_display_options__list_detailed_html_slim__1267502047880366728_70177150759060'
  from action_view/helpers/cache_helper.rb:253:in `write_fragment_for'
  from action_view/helpers/cache_helper.rb:243:in `fragment_for'
  from action_view/helpers/cache_helper.rb:169:in `cache'
  from app/views/works/display_options/_list_detailed.html.slim:6:in `block (2 levels) in _app_views_works_display_options__list_detailed_html_slim__1267502047880366728_70177150759060'
  from active_record/relation/delegation.rb:41:in `each'
  from active_record/relation/delegation.rb:41:in `each'
  from app/views/works/display_options/_list_detailed.html.slim:5:in `block in _app_views_works_display_options__list_detailed_html_slim__1267502047880366728_70177150759060'
  from action_view/helpers/cache_helper.rb:253:in `write_fragment_for'
  from action_view/helpers/cache_helper.rb:243:in `fragment_for'
  from action_view/helpers/cache_helper.rb:169:in `cache'
  from app/views/works/display_options/_list_detailed.html.slim:4:in `_app_views_works_display_options__list_detailed_html_slim__1267502047880366728_70177150759060'
  from action_view/template.rb:159:in `block in render'
  from active_support/notifications.rb:170:in `instrument'
  from action_view/template.rb:354:in `instrument_render_template'
  from action_view/template.rb:157:in `render'
  from action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
  from action_view/renderer/abstract_renderer.rb:44:in `block in instrument'
  from active_support/notifications.rb:168:in `block in instrument'
  from active_support/notifications/instrumenter.rb:23:in `instrument'
  from active_support/notifications.rb:168:in `instrument'
  from action_view/renderer/abstract_renderer.rb:43:in `instrument'
  from action_view/renderer/partial_renderer.rb:333:in `render_partial'
  from action_view/renderer/partial_renderer.rb:312:in `render'
  from action_view/renderer/renderer.rb:49:in `render_partial'
  from action_view/helpers/rendering_helper.rb:37:in `render'
  from app/views/works/popular.html.slim:28:in `_app_views_works_popular_html_slim__1830712642283660183_70177225230800'
```