Call `save!` before run `move_to_top`
To avoid the following error which is caused by updating acts_as_list to 0.9.17.

```
RuntimeError: Locking a record with unpersisted changes is not supported. Use `save` to persist the changes, or `reload` to discard them explicitly.
```